### ISSUE TITLE
Setuptools issue "zipfile.BadZipFile: File is not a zip file"

### ISSUE THREAD

**Issue by gto389** [ClinGen/clincoded#1653]
When doing both local and instance builds `setuptools` runs into an issue:

```
$ sudo -u clincoded python3.4 bootstrap.py -v 2.9.5 --setuptools-version 15.2
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-15.2.zip
Extracting in /tmp/tmpcmosb0p6
Traceback (most recent call last):
  File "bootstrap.py", line 105, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "bootstrap.py", line 105, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

We have reported the issues on the following repo:
https://github.com/pypa/setuptools/issues/1331
https://github.com/pypa/warehouse/issues/3735

The cause of the problem appears to be due to an outage at PyPI's files.pythonhosted.org:
https://status.python.org/incidents/1y1f44q6srh2

A minimum fix that was used to get the build to run successfully was modifying the `buildout.cfg` and the `ez_setup.py`.

`buildout.cfg`:
Add `pypi.org` and `files.pythonhosted.org` under `allow-hosts`, such as:
```
allow-hosts =
    pypi.org
    files.pythonhosted.org
    *.python.org
    github.com
```

`ez_setup.py`:
Update `DEFAULT_VERSION` from `14.3` to `15.2`
Update `DEFAULT_URL` from `https://pypi.python.org/packages/source/s/setuptools/` to `"https://files.pythonhosted.org/packages/28/17/f1b300eeec0405388bfffc51a1efb37c45ad713c978b231f2c24e1a7cee4/"`

**Comment by jimmyzhen** [comment]
Included in the R18 release.
