### ISSUE TITLE
Internal Error causing AWS alerts - "Apache Mapper Parsing Error", "Elasticsearch-prod-ERROR"

### ISSUE THREAD

**Issue by gcheung-SF** [ClinGen/clincoded#2068]
The following error was found during indexing the history object when a case-segregation extra-evidence (with new format) was created.

Traceback (most recent call last):
  File "/srv/clincoded/src/contentbase/elasticsearch/indexer.py", line 198, in update_object
    request_timeout=60,
  File "/srv/clincoded/eggs/elasticsearch-1.7.0-py3.4.egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/srv/clincoded/eggs/elasticsearch-1.7.0-py3.4.egg/elasticsearch/client/__init__.py", line 261, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/srv/clincoded/eggs/elasticsearch-1.7.0-py3.4.egg/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/srv/clincoded/eggs/elasticsearch-1.7.0-py3.4.egg/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/srv/clincoded/eggs/elasticsearch-1.7.0-py3.4.egg/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'MapperParsingException[failed to parse [embedded.primary.source]]; nested: ElasticsearchIllegalArgumentException[unknown property [data]]; ')

**Comment by wrightmw** [comment]
In R29 release.
